CREATE TABLE emails(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EMAIL TEXT NOT NULL,
  UNIQUE(EMAIL) 
);

CREATE TABLE planets(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PLANET_NAME TEXT NOT NULL,
  DISC_FACILITY TEXT NOT NULL,
  RELEASE_DATE TEXT NOT NULL,
  UNIQUE(PLANET_NAME, DISC_FACILITY, RELEASE_DATE)
);